global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'default'

receivers:
  - name: 'default'
    # You can configure real alert notifications like email/Slack later
    # For now, this ensures alerts are routed
