# docker-compose.yml (updated)
version: '3.8'
services:
  my-web-app:
    build: ./app
    ports:
#      - "5000:5000"
      - "8000:8000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
